// ===========================================================
// DATABASE
// ===========================================================

const SUPABASE_URL = 'https://hfusmrnvblrzezllvlec.supabase.co';

const SUPABASE_KEY = 'sb_publishable_anWXUvGCVbF821Co8VQsLQ_PujwsaUn';

let supabaseClient = null;

const ESTRUTURAS_SQL = `-- ===========================================================
-- 15/06/2026 - Segurança: liberação de telas por usuário
-- Execute no SQL Editor do Supabase.
-- ===========================================================

create table if not exists public.usuario_permissoes (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  secao text not null,
  criado_em timestamp without time zone not null default now(),
  criado_por text,
  constraint usuario_permissoes_usuario_secao_uk unique (usuario_id, secao)
);

comment on table public.usuario_permissoes is 'Telas liberadas para cada usuário do sistema.';
comment on column public.usuario_permissoes.usuario_id is 'ID do usuário da tabela usuarios.';
comment on column public.usuario_permissoes.secao is 'Chave da tela liberada no menu do sistema.';

alter table public.usuario_permissoes enable row level security;

drop policy if exists usuario_permissoes_select_all on public.usuario_permissoes;
drop policy if exists usuario_permissoes_insert_all on public.usuario_permissoes;
drop policy if exists usuario_permissoes_update_all on public.usuario_permissoes;
drop policy if exists usuario_permissoes_delete_all on public.usuario_permissoes;

create policy usuario_permissoes_select_all
on public.usuario_permissoes
for select
to anon, authenticated
using (true);

create policy usuario_permissoes_insert_all
on public.usuario_permissoes
for insert
to anon, authenticated
with check (true);

create policy usuario_permissoes_update_all
on public.usuario_permissoes
for update
to anon, authenticated
using (true)
with check (true);

create policy usuario_permissoes_delete_all
on public.usuario_permissoes
for delete
to anon, authenticated
using (true);

-- ===========================================================
-- 15/06/2026 - PDV: cancelamento de vendas
-- ===========================================================

alter table public.vendas
  add column if not exists cancelada boolean not null default false,
  add column if not exists cancelado_em timestamp without time zone,
  add column if not exists cancelado_por text,
  add column if not exists cancel_obs text;

comment on column public.vendas.cancelada is 'Indica se a venda foi cancelada sem excluir o histórico.';
comment on column public.vendas.cancelado_em is 'Data e hora local do cancelamento da venda.';
comment on column public.vendas.cancelado_por is 'Usuário administrador que autorizou o cancelamento.';
comment on column public.vendas.cancel_obs is 'Motivo informado para o cancelamento da venda.';
`;
